"""init

Revision ID: 369167cfdb09
Revises: 
Create Date: 2026-05-09 22:55:05.813009
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '369167cfdb09'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prompt_experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('variant_a', sa.Text(), nullable=False),
    sa.Column('variant_b', sa.Text(), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('winner', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenic_areas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('geo_polygon', sa.JSON(), nullable=True),
    sa.Column('default_persona_id', sa.String(length=64), nullable=True),
    sa.Column('atmosphere', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('openid', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('interest_vec', sa.JSON(), nullable=True),
    sa.Column('location_consent', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('admin_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenic_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_scenic_id'), 'documents', ['scenic_id'], unique=False)
    op.create_table('landmarks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenic_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('avg_duration_min', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('qr_token', sa.String(length=200), nullable=True),
    sa.Column('visual_features', sa.Text(), nullable=True),
    sa.Column('visual_embedding', sa.JSON(), nullable=True),
    sa.Column('reference_photos', sa.JSON(), nullable=False),
    sa.Column('emergency_nearby', sa.JSON(), nullable=False),
    sa.Column('audio_cache_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_landmarks_scenic_id'), 'landmarks', ['scenic_id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenic_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('voice_id', sa.String(length=120), nullable=False),
    sa.Column('avatar_id', sa.String(length=120), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_scenic_id'), 'personas', ['scenic_id'], unique=False)
    op.create_table('user_trails',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('scenic_id', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_trails_scenic_id'), 'user_trails', ['scenic_id'], unique=False)
    op.create_index(op.f('ix_user_trails_user_id'), 'user_trails', ['user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('sparse_vector', sa.Text(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_doc_id'), 'chunks', ['doc_id'], unique=False)
    op.create_table('landmark_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('from_id', sa.String(length=64), nullable=False),
    sa.Column('to_id', sa.String(length=64), nullable=False),
    sa.Column('walk_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['landmarks.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['landmarks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landmark_edges_from_id'), 'landmark_edges', ['from_id'], unique=False)
    op.create_index(op.f('ix_landmark_edges_to_id'), 'landmark_edges', ['to_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('scenic_id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['scenic_id'], ['scenic_areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_scenic_id'), 'sessions', ['scenic_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audio_uri', sa.Text(), nullable=True),
    sa.Column('asr_ms', sa.Integer(), nullable=True),
    sa.Column('llm_ms', sa.Integer(), nullable=True),
    sa.Column('tts_ms', sa.Integer(), nullable=True),
    sa.Column('retrieved_chunks', sa.JSON(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_sessions_scenic_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_landmark_edges_to_id'), table_name='landmark_edges')
    op.drop_index(op.f('ix_landmark_edges_from_id'), table_name='landmark_edges')
    op.drop_table('landmark_edges')
    op.drop_index(op.f('ix_chunks_doc_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_user_trails_user_id'), table_name='user_trails')
    op.drop_index(op.f('ix_user_trails_scenic_id'), table_name='user_trails')
    op.drop_table('user_trails')
    op.drop_index(op.f('ix_personas_scenic_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_landmarks_scenic_id'), table_name='landmarks')
    op.drop_table('landmarks')
    op.drop_index(op.f('ix_documents_scenic_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('scenic_areas')
    op.drop_table('prompt_experiments')
    op.drop_table('admins')
    # ### end Alembic commands ###

